repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/AleksaC/terraform-py
    rev: v1.9.0
    hooks:
      - id: tf-fmt
