name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cameronhudson8/pipeline-containers:2025-08-02T21-56-59Z
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pre-commit checks
        run: |
          git config --global --add safe.directory "${PWD}"
          pre-commit run --all-files
